### ISSUE TITLE
Failed to load agent library

### ISSUE THREAD

**Issue by jlming6** [jrudolph/perf-map-agent#16]
Hi guys,

I used Java(TM) SE Runtime Environment (build 1.8.0_60-ea-b25)
and run ./create-java-perf-map.sh $pid

got:

Exception in thread "main" com.sun.tools.attach.AgentLoadException: Failed to load agent library
	at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:224)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:58)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentPath(HotSpotVirtualMachine.java:88)
	at net.virtualvoid.perf.AttachOnce.loadAgent(AttachOnce.java:39)
	at net.virtualvoid.perf.AttachOnce.main(AttachOnce.java:33)

Any idea?

Thanks so much.

**Comment by lamplet** [comment]
I got the same error. Because libperfmap.so is 64 bit, and java is 32 bit. I remake a 32 bit so, then the error is gone.
