### ISSUE TITLE
Trouble to attach with high PID value

### ISSUE THREAD

**Issue by ymartin59** [jrudolph/perf-map-agent#89]
I am facing this issue with trying to load agent into JVM when system process PID out of integer range:

```
/usr/lib/jvm/java-8-oracle/bin/java -cp attach-main.jar:/usr/lib/jvm/java-8-oracle/lib/tools.jar net.virtualvoid.perf.AttachOnce 115323
Exception in thread "main" java.io.IOException: Non-numeric value found - int expected
	at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:299)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:63)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentPath(HotSpotVirtualMachine.java:88)
	at net.virtualvoid.perf.AttachOnce.loadAgent(AttachOnce.java:51)
	at net.virtualvoid.perf.AttachOnce.main(AttachOnce.java:34)
```

Is there any other work-around than reboot Linux?

Generally speaking, is this "integer" PID restriction for hotspot VM attachment has been fixed in any recent Java 8 or OpenJDK version?

**Comment by jrudolph** [comment]
When I saw error like this the last time, it was a mismatch between the target JDK and the tools.jar. The attach protocol is not guaranteed to be compatible between JDKs.

For me using "long" (> 65536) PIDs works in general.

**Comment by Number1loonastan** [comment]
I got this issue too but the process i want to attach only about PID 181 :( i run out of options can someone save me....

**Comment by lc76226zq** [comment]
I also encountered this issue, but I checked the JDK version to resolve the issue, because the program I started uses JDK 11 but the system defaults to JDK 8.
